spring.application.name=journal
spring.data.mongodb.uri=mongodb+srv://saurabhkoridev_db_user:Gvmx6FZ1NMjCl6eC@cluster0.6ebgesh.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
server.port=8002
#spring.data.mongodb.database=journaldb
server.address=localhost

#test1
spring.data.mongodb.auto-index-creation=true
springdoc.swagger-ui.path=/swagger